version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: mqtt-broker
    hostname: rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
      - "1883:1883"    # MQTT port
      - "15675:15675"  # MQTT over WebSocket
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    command: bash -c "rabbitmq-plugins enable rabbitmq_mqtt rabbitmq_web_mqtt rabbitmq_auth_backend_http && rabbitmq-server"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5